---

sudo: required

services:
  - docker

language: python
#python:
#  - "2.7"

before_install:
  - docker pull solita/ubuntu-systemd:bionic
  # - make bin/python

script:
  - which python
  - python --version
  - lsb_release -a
